version: "3"

services:
  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 127.0.0.1:9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/:/etc/grafana/:ro
    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - prometheus

  api:
    build: .
    depends_on:
      - prometheus
    expose:
      - 9090
    command: npm start
    ports:
      - 127.0.0.1:9999:9090