sudo: false

language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run dist

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"

branches:
  only:
    - develop
    - master