{
 "title": "Autometric",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(autometric_registers_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Autometric Registers",
   "type": "singlestat",
   "description": "Number of registers",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "autometric_registers_total" }
   ]
  },
  {
   "title": "Autometric Counters",
   "type": "singlestat",
   "description": "Number of registers",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "autometric_counters_total" }
   ]
  },
  {
   "title": "Autometric Summaries",
   "type": "singlestat",
   "description": "Number of summaries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "autometric_summaries_total" }
   ]
  }
 ]
}