{
 "title": "Radio",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "mainInterval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(radio_stream_pipe_chunk_sizes_bytes, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Middleware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data send",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(radio_stream_middleware_outgoing_bytes_sum{quality=\"lq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Low Quality {{ broadcaster }}"
    },
    {
     "expr": "rate(radio_stream_middleware_outgoing_bytes_sum{quality=\"hq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Heigh Quality {{ broadcaster }}"
    }
   ]
  },
  {
   "title": "Requests per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(radio_stream_middleware_calls_total{quality=\"lq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Low Quality {{ broadcaster }}"
    },
    {
     "expr": "rate(radio_stream_middleware_calls_total{quality=\"hq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Heigh Quality {{ broadcaster }}"
    }
   ]
  },
  { "title": "Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Data send",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(radio_stream_pipe_chunk_sizes_bytes_sum{quality=\"lq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Low quality {{broadcaster}}"
    },
    {
     "expr": "rate(radio_stream_pipe_chunk_sizes_bytes_sum{quality=\"hq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Heigh quality {{broadcaster}}"
    }
   ]
  },
  {
   "title": "Chunks per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(radio_stream_pipe_chunk_sizes_bytes_count{quality=\"lq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Low quality {{ broadcaster }}"
    },
    {
     "expr": "rate(radio_stream_pipe_chunk_sizes_bytes_count{quality=\"hq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Heigh quality {{ broadcaster }}"
    }
   ]
  },
  {
   "title": "Elapsed time between chunks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(radio_stream_pipe_elapsed_time_ms_sum{quality=\"lq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Low quality {{ broadcaster }}"
    },
    {
     "expr": "rate(radio_stream_pipe_elapsed_time_ms_sum{quality=\"hq\",instance=\"$instance\"}[$mainInterval])",
     "legendFormat": "Heigh quality {{ broadcaster }}"
    }
   ]
  }
 ]
}